trailingComma: 'es5'
printWidth: 120
tabWidth: 4
semi: true
singleQuote: true
bracketSpacing: false
overrides:
  - files: ['*.md', '*.json', '*.yml', '*.yaml']
    options: {tabWidth: 2}
plugins:
  - 'prettier-plugin-jsdoc'
