---
name: TypeDoc

on:
  push:
    branches:
      - master

jobs:
  typedoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v18.x
        uses: actions/setup-node@v2
        with:
          node-version: v18.x
      - name: Generate
        run: |
          npm i -g typedoc
          npm ci
          typedoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: typedoc
          folder: ./typedoc
